/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.howest.groep12.geowars.view.game;

import be.howest.groep12.geowars.Settings.SettingsModel;
import be.howest.groep12.geowars.Settings.StyleSettings;
import java.awt.CardLayout;
import java.awt.Polygon;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Jonas Lauwers
 */
public class GamePanel extends javax.swing.JPanel implements Observer {
    
    private testActor game;

    /**
     * Creates new form GamePanel
     */
    public GamePanel(SettingsModel settings) {
        initGame();
        initComponents();
        this.setBackground(settings.getBackgroundColor());
        this.setForeground(settings.getTextColor());
        settings.addColorObserver(this);
        drawPanel1.setGame(game.getDrawables(), game);
        drawPanel1.setFocusable(true);
    }
    
    public void initGame(testActor game) {
        
    }
    
    public void initGame() {        
        game = new testActor(10, 10, new Polygon());
        game.addDrawable(new testActor(20, 20, new Polygon(new int[] {12,14,18}, new int[] {10,12,10}, 3)));
        game.addDrawable(new testActor(25, 40, new Polygon(new int[] {22,24,28}, new int[] {20,22,20}, 3)));
        game.addDrawable(new testActor(30, 30, new Polygon(new int[] {32,34,38}, new int[] {30,32,30}, 3)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel1 = new be.howest.groep12.geowars.view.game.drawPanel();
        gameButton1 = new be.howest.groep12.geowars.view.GameButton();

        setBackground(new java.awt.Color(0, 0, 153));
        setFocusable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        drawPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        drawPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                drawPanel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout drawPanel1Layout = new javax.swing.GroupLayout(drawPanel1);
        drawPanel1.setLayout(drawPanel1Layout);
        drawPanel1Layout.setHorizontalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        drawPanel1Layout.setVerticalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        gameButton1.setText("Exit game");
        gameButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(drawPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(gameButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(drawPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(gameButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drawPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drawPanel1KeyPressed

    }//GEN-LAST:event_drawPanel1KeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        game.setX(game.getX()+1);
    }//GEN-LAST:event_formMouseClicked

    private void gameButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButton1ActionPerformed
        drawPanel1.endGame();
        CardLayout test = (CardLayout) getParent().getLayout();
        test.show(getParent(), "SinglePlayerMenu");
        initGame();
        drawPanel1.setGame(game.getDrawables(), game);
    }//GEN-LAST:event_gameButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private be.howest.groep12.geowars.view.game.drawPanel drawPanel1;
    private be.howest.groep12.geowars.view.GameButton gameButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        StyleSettings setting = (StyleSettings) o;
        this.setBackground(setting.getBackgroundColor());
        this.setForeground(setting.getTextColor());
        
    }
}
