/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.howest.groep12.geowars.gui;

import be.howest.groep12.geowars.model.Player;

/**
 *
 * @author Jonas Lauwers
 */
public class MainFrame extends javax.swing.JFrame {
    
    public final int WIDTH = 800;
    public final int HEIGHT = 600;
    
    private final SettingsModel settings;
    private Player player;
    //private Game game;

    /**
     * Creates new form MainFrame
     * @param settings
     */
    public MainFrame(SettingsModel settings) {
        this.settings = settings;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geowars");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
